image:
  file: .gitpod.Dockerfile

tasks:
  - init: mysql --version
  - name: Start MySQL
    command: >
      sudo service mysql start && 
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS mydatabase;"
ports:
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - formulahendry.vscode-mysql
